{% set name = "clawpack" %}
{% set version = "5.8.2" %}

{% set mpi = mpi %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/releases/download/v{{ version }}/{{ name }}-v{{ version }}.tar.gz
  sha256: 06895806688e85aab141151f6d2077d67faf15595d3e6fd88a4d91eddceb88b2

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 1
  skip: yes  # [win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
  host:
    - pip
    - python
    - numpy
    - six
    - {{ mpi }}
  run:
    - {{ mpi }}
    - h5py * mpi_{{ mpi }}_*
    - python
    - six
    - numpy
    - scipy
    - matplotlib-base
    - mpi4py
    # temporary workaround to get stuff to work on osx-arm
    - petsc4py  # [not (osx and build_platform != target_platform)]
    - {{ compiler('c') }}  # [osx and build_platform != target_platform]
    - {{ compiler('cxx') }}  # [osx and build_platform != target_platform]
    - {{ compiler('fortran') }}  # [osx and build_platform != target_platform]

test:
  imports:
    - clawpack.pyclaw
    - clawpack.petclaw
    - clawpack.pyclaw.fileio.hdf5
    - clawpack.riemann.euler_4wave_2D
  requires:
    - pip
  commands:
    - pip check
    - python -c "from clawpack.pyclaw import examples; claw = examples.shock_bubble_interaction.setup(); claw.run()"


about:
  home: https://github.com/clawpack/clawpack
  summary: Package for solving hyperbolic systems of partial differential equations
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ngam
